
#  Author: Rafael Ramirez & Matt D Jaranilla
#  RedID: 825477088 & 825452453

# for c++ compiler
CXX = g++

# -std=c++11  C/C++ variant to use, e.g. C++ 2011
# -Wall       show the necessary warning files
# -g3         include information for symbolic debugger e.g. gdb 
CXXFLAGS = -std=c++11 -Wall -g3 -c

# object files
OBJS = main.o 

# Program name
PROGRAM = demandpaging

# instead of calling countsubstrings, can just make all
all: $(PROGRAM)

# The program depends upon its object files
#remmber to choose one
$(PROGRAM) : $(OBJS)
	$(CXX) -o $(PROGRAM) $^

main.o : main.cpp
	$(CXX) $(CXXFLAGS) main.cpp

clean :
	rm -f *.o $(PROGRAM)


