
#  Author: Rafael Ramirez & Matt D Jaranilla
#  RedID: 825477088 & 825452453

# for c++ compiler
CXX = g++

# -std=c++11  C/C++ variant to use, e.g. C++ 2011
# -Wall       show the necessary warning files
# -g3         include information for symbolic debugger e.g. gdb 
CXXFLAGS = -std=c++11 -Wall -g3 -c

# object files
OBJS = main.o vaddr_tracereader.o log_helpers.o pagetable.o pagereplacement.o

# Program name
PROGRAM = demandpaging

# instead of calling countsubstrings, can just make all
all: $(PROGRAM)

# The program depends upon its object files
#remmber to choose one
$(PROGRAM) : $(OBJS)
	$(CXX) -o $(PROGRAM) $^

main.o : main.cpp
	$(CXX) $(CXXFLAGS) main.cpp

vaddr_tracereader.o :vaddr_tracereader.h vaddr_tracereader.cpp
	$(CXX) $(CXXFLAGS) vaddr_tracereader.cpp

log_helpers.o : log_helpers.h log_helpers.cpp
	$(CXX) $(CXXFLAGS) log_helpers.cpp

pagetable.o : pagetable.h pagetable.cpp
	$(CXX) $(CXXFLAGS) pagetable.cpp

pagereplacement.o : pagereplacement.h pagereplacement.cpp
	$(CXX) $(CXXFLAGS) pagereplacement.cpp


clean :
	rm -f *.o $(PROGRAM)


